server:
  port: 5051
spring:
  dataSource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Password12
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    
  